#!/usr/bin/env ruby
class Installer
	def self.deps
		puts "==> Installing dependencies"
		system("sudo apt-get install compiz compiz-plugins kupfer cairo-dock compton gnome-screenshot lwm vala-panel* hsetroot")
		puts "=> Dependencies installed"
	end
	def self.build
		puts "==> Building..."
		system("sudo mkdir /usr/local/share/oblivion")
		system("sudo mv ./setup-sources/sh/oblivion.sh /usr/local/share/oblivion/")
		system("sudo mv ./setup-sources/desktop/oblivion.desktop /usr/share/xsessions/")
		system("sudo mv ./setup-sources/bg.png /usr/local/share/oblivion/")
		system("chmod +x /usr/local/share/oblivion/oblivion.sh")
	end
	def self.finish
		puts "OBLIVION BUILDED WITH SUCESS!"
	end
end

Installer.deps
Installer.build
Installer.finish
